<!doctype html>
<?php //Conditional comment for mobile ie7 http://blogs.msdn.com/b/iemobile/ ;?>
<!--[if IEMobile 7 ]>    <html class="no-js iem7"> <![endif]-->
<!--[if (gt IEMobile 7)|!(IEMobile)]><!--> <html class="no-js"> <!--<![endif]-->
<head>
<meta charset="utf-8">

<title>Enotria</title>
<meta name="description" content="">
<meta name="author" content="">

<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="width=device-width, target-densitydpi=160dpi, initial-scale=1.0">

<link rel="canonical" href="/"><!--remove if no search engine access beyond login/signup pages-->

<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/img/h/apple-touch-icon.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/m/apple-touch-icon.png">
<link rel="apple-touch-icon-precomposed" href="/img/l/apple-touch-icon-precomposed.png">
<link rel="shortcut icon" href="/img/l/apple-touch-icon.png">

<!-- Styles -->
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" media="print" href="/css/print.css">
<!-- For Retina displays - loads higher resolution images-->
<link rel="stylesheet" media="only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (-o-min-device-pixel-ratio: 3/2), only screen and (min-device-pixel-ratio: 1.5)" href="/css/2x.css">

<!-- JavaScript -->
<script src="js/libs/modernizr-2.0.6.min.js"></script>


<!--iOS. Delete if not required -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<!-- this script will cause links to external sites to open in mobile safari when the site is being viewed in standalone/webapp mode-->
<script>(function(a,b,c){if(c in b&&b[c]){var d,e=a.location,f=/^(a|html)$/i;a.addEventListener("click",function(a){d=a.target;while(!f.test(d.nodeName))d=d.parentNode;"href"in d&&(d.href.indexOf("http")||~d.href.indexOf(e.host))&&(a.preventDefault(),e.href=d.href)},!1)}})(document,window.navigator,"standalone")</script>
<link rel="apple-touch-startup-image" href="/img/l/splash.png">

<!--Microsoft. Delete if not required -->
<meta http-equiv="cleartype" content="on">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<!--End header include-->